### ISSUE TITLE
Page 2 : rises -> raises

### ISSUE THREAD

**Issue by babafou** [jackdoe/programming-for-kids#27]
In the example in page 2, rises should be replaced by raises:

$ cat 03.txt | grep "rises" | wc -l

because the rest of the text assumes it reads raises.

By the way, this command is a useless use of cat and double quotes are not needed so it should also be replaced with:

$ grep raises 03.txt | wc -l

In the same page, conntents should be replaced by contents.

**Comment by jackdoe** [comment]
thanks
the typos is going to be fixed in the next version

I specifically overuse pipes and quotes because it is easier to teach like that, and when i play with my daughter i play a version of the game where i pick a random card and inject it in the pipe chain, or swap cards. It helps to think as "ok first i need to stream the file, then i start to apply my filters one by one'.

I also overuse quotes because i dont want to overload her with why `grep raises` works but `grep hello world` says it can not find `world`. It also helps to think as the "oh i want to pass this string to grep" rather than overthinking the difference between the word `grep` and the word `raises`.
