### ISSUE TITLE
Translate the book into other languages

### ISSUE THREAD

**Issue by psjnek** [jackdoe/programming-for-kids#31]
Hi, I think that "Programming for Kids" should be translated into other languages to make it more accessible for those who don't speak English. This could be included in some sort of to-do list.

Thanks
WebSnke

**Comment by jackdoe** [comment]
Hi
Do you mean the card games or the book.md file?

Me and my daughter are not native english speakers, but I decided to teach her in english because the amount of youtube lessons and guides in english is just phenomenal. This of course makes the task of teaching much harder.

Your thoughts are almost constrained by language, how things interact and how you think about them, for example in a language where things have grammatical gender (like spanish, french etc) even variable names and function names have subtle difference, and the programs themselves look a bit different. Or subject-object-verb (japanese) languages versus subject-verb-object (english) (https://en.wikipedia.org/wiki/Subject%E2%80%93verb%E2%80%93object_word_order) you can see it in people's code, how methods are called or how class hierarchy looks.

So I think great care is needed to make a good translation of programming concepts, and I am not sure how to approach it so the result is not much worse than not translating it at all.

**Comment by psjnek** [comment]
> So I think great care is needed to make a good translation of programming concepts, and I am not sure how to approach it so the result is not much worse than not translating it at all.

Yeah, translating it won't be easy. As a German myself, I often prefer documentation in English as the German translation isn't very helpful. Moreover, this project would have to get a lot more people on board to translate it properly.
